language: node_js
node_js:
  - "stable"
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
install:
    - npm install
script: 
- node Server.js
after_script:
  - curl http://localhost:3000/close
