language: node_js
node_js:
  - "stable"
services:
  - mongodb
addons:
  sauce_connect:
    username: "AmmarahCassim"
    access_key: "24302255-f2d7-46f5-ac1c-9c90ec0eff11"
install:
    - npm install
before_script:
  - chmod +x testfiles/test1.js
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - node Server.js
  - sleep 50
script: 
 - pkill node
