language: node_js
node_js:
  - "6"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
install:
    - npm install
script: 
- node Server.js
